Repository geoelements/gns, pull requests merged in 2021-12, with the labels that each got.

#1 :books: create env on frontera
  README.md
  venv.sh
Labels: Type: Documentation

#8 Fixes #7 stack error size
  .circleci/config.yml
  gns/train.py
  requirements.txt
Labels: Priority: High, Type: Bug

#9 TACC Environment Setup
  .gitignore
  README.md
  build_venv.sh
  gns/train.py
  slurm_scripts/render.sh
  slurm_scripts/rollout.sh
  slurm_scripts/train.sh
  start_venv.sh
  test/test_pytorch.py
  test/test_pytorch_cuda_gpu.py
  test/test_torch_geometric.py
Labels: Priority: Medium, Status: Accepted
